on:
  push:
    branches:    
      - master
name: Build
jobs:
  macOS:
    name: macOS platform
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          git submodule update --init --recursive
          xcodebuild clean test -project DeltaCodec.xcodeproj -scheme DeltaCodec-macOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  iOS:
    name: iOS platform
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          git submodule update --init --recursive
          xcodebuild clean test -project DeltaCodec.xcodeproj -scheme DeltaCodec-iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  tvOS:
    name: tvOS platform
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          git submodule update --init --recursive
          xcodebuild clean test -project DeltaCodec.xcodeproj -scheme DeltaCodec-tvOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
