on:
  push:
    branches:    
      - main
name: Build
jobs:
  macOS:
    name: macOS platform
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          git submodule update --init --recursive
          xcodebuild clean test -project DeltaCodec.xcodeproj -scheme DeltaCodec-macOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  iOS:
    name: ARM
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          git submodule update --init --recursive
          xcodebuild clean test -project DeltaCodec.xcodeproj -scheme DeltaCodec-iOS -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    env:
      destination: ${{ matrix.destination }}
  tvOS:
    name: ARM
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=tvOS Simulator,OS=13.3,name=Apple TV']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          git submodule update --init --recursive
          xcodebuild clean test -project DeltaCodec.xcodeproj -scheme DeltaCodec-tvOS -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    env:
      destination: ${{ matrix.destination }}
